/*
 * generated by Xtext 2.37.0.M0
 */
package dk.sdu.bdd.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBddDslScopeProvider extends DelegatingScopeProvider {
}
