/*
 * generated by Xtext 2.36.0
 */
package dk.sdu.bdd.xtext.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link BddDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractBddDslWebModule extends DefaultWebModule {

}
